presentations/readme.md
(I got a file-not-found error when I clicked to see the slides)
=> Fix links to match filenames

examples/Bodleian Ballads/Example of two ballads.md
Added a WEMI example diagram for two ballads.
=> Create Example of two ballads.md

examples/comics/openwemi-daredevil-ex1.json, examples/comics/openwemi-daredevil-ex2.json, examples/comics/openwemi-daredevil-ex3.json
Updated comics example to include openWEMI:responsibleFor; fixed several URIs; changed schema:issueNumber to cbo:issueNumber in ex3.
=> Update comics example

vocab/openWEMI.ttl
Adds relatedEndeavor, relatedWork, relatedExpression, relatedManifestation, and relatedItem
=> Add related entity properties

vocab/openWEMI.ttl
Changes `ResponsibleEntity` from a class representing an agent of some sort, to a property connecting the `Endeavor` to... whatever
=> Change ResponsibleEntity to responsibleEntity

examples/bibo/burke-connections-bibo-bibframe-opengraph.ttl
This is a _really_ rough draft
=> James Burke's Connections: BIBO, Bibframe, and Open Graph of TV series

examples/comics/alignment/.gitignore, examples/comics/alignment/cbo-openwemi-ex1.ttl
Update comics alignment poc with import of openwemi vocab ttl from github.
=> Update comics alignment poc with import of openwemi vocab

examples/comics/alignment/.gitignore, examples/comics/alignment/cbo-openwemi-ex1.ttl, examples/comics/alignment/cbo-openwemi.ttl
Add import of openwemi vocab, switch to subPropertyOf for property alignment.
=> Update comics alignment 

vocab/openWEMI.ttl
Fix rdfs:labels for manifests and instantiates properties.
=> Fix labels for manifests and instantiates

vocab/openWEMI.ttl
Fixes a turtle syntax error on line 46, and some formatting issues (double spaces, etc.).
=> Fix turtle syntax error and formatting issues

vocab/openWEMI.ttl
=> Replace owl:ObjectProperty with rdfs:Property

vocab/openWEMI.ttl
Change owl:Class references to rdfs:Class; includes several formatting fixes (extra line breaks, etc.)
=> Change owl:Class to rdfs:Class

vocab/openWEMI.ttl
Adds an openwemi prefix and placeholder URI pointing to GitHub, and replaces all example.org references.
=> Add openwemi prefix and placeholder URI

vocab/openWEMI.ttl
Update temp URI for openWEMI to: https://dcmi.github.io/openwemi/ns#
=> Update temp URI

docs/index.md
Add two schema.org examples, including folded code sections.
=> Add schema.org examples

docs/draft/context.json
This will add  docs/draft/context.json which will be published to https://dcmi.github.io/openwemi/draft/context.json to allow testing JSON-LD examples using that context file. Will send more info in email.
=> Add JSON-LD context file

docs/index.md
Small edit: I on reading it I found that second table that was not displaying correctly just repeated what was in the first table, so I deleted it and the associated paragraph.
=> rm paragraph that repeated some of previous paragraph

docs/index.md
Decided in March 27, 2024 meeting
=> changes to "entity"

docs/index.md
Removed note about temporary namespace; changed namespace URI in examples. Removed "Primer" from title.
=> New namespace

docs/draft/context.json, docs/draft/readme.md, docs/draft/specification.md, docs/index.md
Making changes so that the github.io site is set up as a drafting site.
=> Phil drafting site
